#define GIT_SUMM v3.0.3
#define GIT_HASH e7eb16e1
#define GIT_BRANCH r3.0
#define GIT_DATE 2025-05-23 23:43:28 +0800
#define DEEPMD_ROOT 
#define BACKEND_INCLUDE_DIRS 
#define BACKEND_LIBRARY_PATH /data1/Work/DeepMD/deepmd_venv/lib64/python3.9/site-packages/tensorflow
#define DPMD_CVT_STR(...) #__VA_ARGS__
#define DPMD_CVT_ASSTR(X) DPMD_CVT_STR(X)
#define STR_GIT_SUMM DPMD_CVT_ASSTR(GIT_SUMM)
#define STR_GIT_HASH DPMD_CVT_ASSTR(GIT_HASH)
#define STR_GIT_BRANCH DPMD_CVT_ASSTR(GIT_BRANCH)
#define STR_GIT_DATE DPMD_CVT_ASSTR(GIT_DATE)
#define STR_FLOAT_PREC DPMD_CVT_ASSTR(FLOAT_PREC)
#define STR_DEEPMD_ROOT DPMD_CVT_ASSTR(DEEPMD_ROOT)
#define STR_BACKEND_INCLUDE_DIRS DPMD_CVT_ASSTR(BACKEND_INCLUDE_DIRS)
#define STR_BACKEND_LIBRARY_PATH DPMD_CVT_ASSTR(BACKEND_LIBRARY_PATH)
